SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `calcdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `calcdb` ;

-- -----------------------------------------------------
-- Table `calcdb`.`calc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calcdb`.`calc` (
  `idcalc` INT NOT NULL AUTO_INCREMENT,
  `xxx` VARCHAR(45) NULL,
  `yyy` VARCHAR(45) NULL,
  `zzz` VARCHAR(45) NULL,
  `calcres` VARCHAR(45) NULL,
  PRIMARY KEY (`idcalc`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
